### PR TITLE
Refs [TASK] [40086] Xây dựng giao diện HomePage ( HomePage Banner )

### PR DESCRIPTION
**Pull request by hieumn299**
https://edu-redmine.sun-asterisk.vn/issues/40086

### CODE REVIEW

**Comment by hieumn299** [comment]
ready

**Comment by manhnt-0960** [comment]
commented

**Comment by hieumn299** [comment]
ready

**Comment by manhnt-0960** [comment]
conflicted

**Comment by hieumn299** [comment]
ready

**Pull request merged**
